version: '3.5'
services:
  app:
    image: webdevops/php-nginx-dev:7.4
    restart: unless-stopped
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=-1
    volumes:
      - /home/jtodd/projects/pi-announcer/src/web:/app
      - /home/jtodd/projects/pi-announcer/drops:/var/drops
      - ~/.ssh:/root/.ssh:ro
    ports:
      - 8000:80
